### ISSUE TITLE
AAS-GUI does not show submodel contents

### ISSUE THREAD

**Issue by rosseboe** [eclipse-basyx/basyx-applications#116]
We are exploring the latest Basyx version, and have it deployed on our kubernetes based platform (https://radix.equinor.com). 

the setup is mostly working, but we experience something similar as described in issue #109.

We have uploaded two shells to the environment, but when clicking on a shell we get an error message. 
![image](https://github.com/eclipse-basyx/basyx-applications/assets/20611258/37413a08-097c-4017-b518-67f80c42b93e)

dev console says the submodel is correctly fetched via
`https://{aasenvironment}/shells/aHR0cHM6Ly93YWdvLmNvbS9pZHMvYWFzLzc1MC04OTE`

However, the dev console gives an error: 

```
TypeError: Cannot read properties of undefined (reading 'id')
    at index-DyvK74d_.js:4012:2352
    at renderList (index-DyvK74d_.js:26:19838)
    at index-DyvK74d_.js:4012:2281
    at Object.S [as default] (index-DyvK74d_.js:26:5236)
    at Proxy.<anonymous> (index-DyvK74d_.js:48:4853)
    at renderComponentRoot (index-DyvK74d_.js:26:5685)
    at ReactiveEffect.Xi [as fn] (index-DyvK74d_.js:26:40461)
    at ReactiveEffect.run (index-DyvK74d_.js:15:1918)
    at we.update (index-DyvK74d_.js:26:41564)
    at callWithErrorHandling (index-DyvK74d_.js:26:796)


```

Log file:  [1713526815567.log](https://github.com/eclipse-basyx/basyx-applications/files/15039716/1713526815567.log)

GUI: `eclipsebasyx/aas-gui:v2-240327`
Environment: `eclipsebasyx/aas-environment:2.0.0-SNAPSHOT` 
Registry:` eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT`

**Comment by aaronzi** [comment]
I will have a look at this and come back with a solution. In the meantime, you could check if the same problem occurs with `eclipsebasyx/aas-environment:2.0.0-milestone-02`.
Also, I will be releasing a new version of the UI that addresses an issue that is probably related to that.

Another hint because I can see that you are using the WAGO AASs: I think those shells have missing IDs which would also fit with the error you are seeing. But that wouldn't explain why the same thing happens with the example AAS.

**Comment by aaronzi** [comment]
Hello @rosseboe,

we found the problem that caused the issue you are facing. It was caused by a bug in the registry integration feature of the AAS Environment (AAS and Submodel Repository). This bug was fixed in this [PR](https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/265). The changes are now part of the current versions of the [BaSyx off-the-shelf components on Docker Hub](https://hub.docker.com/layers/eclipsebasyx/aas-environment/2.0.0-SNAPSHOT/images/sha256-9ef7ae78878a205e580d19a495469df16de81b321e7911bfb263a931599069aa?context=explore). Please make sure to delete the old images locally because the tag names did not change!

One thing to look out for right now is that the `basyx.externalurl` should have a trailing slash!

It could look like this:
```
basyx.externalurl = https://my-url/aas-env/
```

Please try the new version and check if it fixes the problem.

**Comment by rosseboe** [comment]
thanks for the update. did a small test now, and still see issues. 

First I uploaded the `ExampleV3.aasx` file to the environment without issues. 
when i click one of the shells, I get this error message:
![image](https://github.com/eclipse-basyx/basyx-applications/assets/20611258/301e97db-58b8-433f-9bda-e97bd21e0586)

dev console shows:
```
Request was successful, but received unexpected content type or no content. 
                                    Content-Type: text/html, 
                                    Content-Length: 449

```
the dev console shows the call to `http://{aas-env}/shells/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw/submodel-refs` returns successfully this response:

```
{
    "paging_metadata": {},
    "result": [
        {
            "keys": [
                {
                    "type": "Submodel",
                    "value": "https://example.com/ids/sm/2411_7160_0132_4523"
                }
            ],
            "type": "ExternalReference"
        }
    ]
}
```

but `index-D8IotdOd.js` returns the error text in this part of the code
```

                if (a.ok) {
                    if (a.ok && a.status >= 200 && a.status < 300)
                        return console.error(`Request was successful, but received unexpected content type or no content. 
                                    Content-Type: ${a.headers.get("Content-Type")}, 
                                    Content-Length: ${a.headers.get("Content-Length")}`),
                        {
                            success: !1
                        };
                    throw new Error("Unexpected HTTP status: " + a.status)
   
```

**Comment by aaronzi** [comment]
Thank you for providing me with updated details about the issue. The problem I see here is the Content-Type. The expected Content-Type should be application/json and not text/html. This request `http://{aas-env}/shells/aHR0cHM6Ly9leGFtcGxlLmNvbS9pZHMvc20vMjQxMV83MTYwXzAxMzJfNDUyMw/submodel-refs` is obviously successful which means the AAS Environment works as expected. The next request would be a request to the Submodel Registry to receive the Submodel endpoints. This fails which means that the Submodel Registry could have a configuration issue.

Could you please try to access the following path of the registry (in the browser):

> http://{sm-registry}/submodel-descriptors

I would be interested if you are able to access this endpoint and what it responds with.

**Comment by rosseboe** [comment]
Indeed, there was a problem with my sm-registry: I forgot do add the integration to application.properties in the aas-environment.

`basyx.submodelrepository.feature.registryintegration = http://sm-registry:8084
`

When I added this, the shells are loaded as expected.  Thanks!

**Comment by aaronzi** [comment]
That's good to hear! You are welcome.
